---
kind: pipeline
type: docker
name: app-powerdns

steps:

- name: deploy_local
  pull: never
  image: ${DCAPE_COMPOSE}
  commands:
  - . setup config
  - make db-init
  - make .drone-default
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
